"""
Count tags in your training data directories (which generated by image tag estimation systems
like DeepDanbooru https://github.com/KichangKim/DeepDanbooru).
"""
import os
import re

TAG_FILE_DIR = ''
TAG_FILE_EXT = ''


def rank_counted_tags(tag_frequency: dict[str, int]) -> list[(str, int)]:
    """The higher the frequency, the higher the ranking"""
    return sorted([(k, v) for k, v in tag_frequency.items()], key=lambda tup: tup[1], reverse=True)


def count_tags_frequency() -> dict[str, int]:
    """Basically just read the text files, find tags, then count them."""
    file_dir = TAG_FILE_DIR if TAG_FILE_DIR else './tests/data/count_tags'
    tag_file_ext = TAG_FILE_EXT if TAG_FILE_EXT else 'txt'

    tag_map = dict()

    for filename in [f for f in os.listdir(file_dir) if f.endswith(tag_file_ext)]:
        with open(os.path.join(file_dir, filename), 'r') as file:
            for line in [l.removesuffix('\n') for l in file.readlines()]:
                if ',' in line:
                    tags = re.compile(r'\s*,\s*').split(line)
                else:
                    tags = [line]

                for tag in tags:
                    tag_map[tag] = tag_map.get(tag) + 1 if (tag in tag_map.keys()) else 1

    return tag_map


if __name__ == '__main__':
    print(rank_counted_tags(count_tags_frequency()))
